---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hasura
    spec:
      containers:
        - image: hasura/graphql-engine:v1.2.2
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: "postgresql://postgres:<YourPostgresPassword>@postgresql:5432/postgres"
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: hasura-port
          resources: {}
          readinessProbe:
            httpGet:
              path: /v1/version
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /v1/version
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
